"""Point mark.

An interactive point chart with a quantitative color channel and a smooth
relationship generated by GenomeSpy transforms.
"""

import genome_spy as gs
from genome_spy.datasets._grammar import sincos_data

META = {
    "category": "Basics",
    "tags": ("point", "transform", "encoding"),
    "order": 10,
    "height": 300,
}

data = sincos_data()

chart = (
    gs.Chart(data)
    .transform_formula(expr="sin(datum.x / 4)", as_="sin")
    .transform_formula(expr="cos(datum.x / 5)", as_="cos")
    .mark_point(size=60, filled=True, opacity=0.75)
    .encode(
        x=gs.X("x:Q").scale(zoom=True).title("Position"),
        y=gs.Y("sin:Q").scale(zoom=True).title("sin(x / 4)"),
        color=gs.Color("cos:Q").title("cos(x / 5)"),
    )
    .properties(title="Point mark")
)
