"""Generate the API reference index from the public ``genome_spy`` namespace.

The index lists every public object as an ``autosummary`` entry, so Sphinx
generates one page per object instead of inlining the whole API into a single
document. Groups are derived from the objects themselves rather than a
hand-maintained list, which keeps the index in step with ``genome_spy.__all__``.

Run ``uv run python tools/generate_api_docs.py`` after changing the public API.
``tests/test_docs_api_reference.py`` fails when the committed file is stale.

The API grouping follows Vega-Altair's documentation generator:
https://github.com/vega/altair/blob/main/tools/generate_api_docs.py
"""

from __future__ import annotations

import inspect
from pathlib import Path
from types import FunctionType
from typing import Final

import genome_spy as gs
from genome_spy.chart import TopLevelSpec

REPO_ROOT = Path(__file__).resolve().parent.parent
API_PAGE = REPO_ROOT / "docs" / "api.md"

CHANNELS_MODULE: Final = "genome_spy.schema.channels"
SCHEMA_MODULE: Final = "genome_spy.schema.core"

PAGE_TEMPLATE: Final = """# API reference

<!-- Generated by tools/generate_api_docs.py. Do not edit by hand. -->

Every public object has its own page. Each class page opens with a summary
table of its methods and attributes, followed by the full description of each
one.

Most classes here are generated from the GenomeSpy JSON schema and keep their
upstream names and property names, so
[types used in the grammar](https://genomespy.app/docs/grammar/types/) documents
the same objects.

## Chart and composition

Charts and composed views. Their methods return new objects, so a chart can be
extended without mutating the original.

{toplevel}

## Encoding channels

One class per encoding channel. Pass them to `encode()`, or use the field/type
shorthand such as `"score:Q"` for simple cases.

{channels}

## API functions

Constructors and helpers for composition, encoding definitions, parameters, and
schema objects.

{functions}

## Schema objects

Schema-backed configuration objects accepted by charts, channels, and helpers.

{schema}

## Data sources

`gs.lazy` is a ready-made {{py:class}}`~genome_spy.data.LazyNamespace` instance,
so a lazy source is created with `gs.lazy.bigwig(url)` rather than by
constructing the namespace.

{data}

## Example datasets

Packaged tables used by the gallery examples. See
[example datasets](datasets.md) for their contents and sources.

{datasets}

## Notebook rendering

{notebook}
"""

SECTION_TEMPLATE: Final = """```{{eval-rst}}
.. currentmodule:: {module}

.. autosummary::
   :toctree: generated/{group}/
   :nosignatures:
{template}
{names}
```"""

# ``Locus`` is a locus-channel constructor rather than an ordinary helper, so it
# belongs with the channels. Keeping it out of the function group also avoids a
# stub-file collision with ``locus`` on case-insensitive filesystems.
CHANNEL_CONSTRUCTORS: Final = ("Locus",)
FUNCTION_LIKE_OBJECTS: Final = ("datum", "expr")


def _public_objects() -> list[tuple[str, object]]:
    """Return every exported ``genome_spy`` object, skipping dunder names."""
    return [
        (name, getattr(gs, name))
        for name in sorted(gs.__all__)
        if not name.startswith("__")
    ]


def top_level_objects() -> list[str]:
    """Chart classes and the imported-view wrapper."""
    return sorted(
        name
        for name, obj in _public_objects()
        if inspect.isclass(obj)
        and (issubclass(obj, TopLevelSpec) or obj is gs.ImportedView)
    )


def encoding_channels() -> list[str]:
    """Generated encoding-channel wrappers and channel constructors."""
    return sorted(
        name
        for name, obj in _public_objects()
        if (inspect.isclass(obj) and obj.__module__ == CHANNELS_MODULE)
        or name in CHANNEL_CONSTRUCTORS
    )


def schema_objects() -> list[str]:
    """Schema wrappers and schema-backed authoring value classes."""
    return sorted(
        name
        for name, obj in _public_objects()
        if (inspect.isclass(obj) and obj.__module__ == SCHEMA_MODULE)
        or obj in (gs.Expression, gs.Parameter)
    )


def api_functions() -> list[str]:
    """Public module-level functions, except the channel constructors."""
    return sorted(
        name
        for name, obj in _public_objects()
        if (isinstance(obj, FunctionType) or name in FUNCTION_LIKE_OBJECTS)
        and name not in CHANNEL_CONSTRUCTORS
    )


def notebook_objects() -> list[str]:
    """Classes that render charts in notebook frontends."""
    return ["JupyterChart"]


def _section(
    names: list[str],
    *,
    group: str,
    module: str = "genome_spy",
    template: str | None = None,
) -> str:
    """Render one autosummary block."""
    if not names:
        raise ValueError(f"No objects found for the {group!r} API section.")
    body = "\n".join(f"   {name}" for name in names)
    template_option = f"   :template: {template}\n" if template else ""
    return SECTION_TEMPLATE.format(
        module=module, group=group, template=template_option, names=body
    )


def render_api_page() -> str:
    """Render the complete API reference index."""
    return PAGE_TEMPLATE.format(
        toplevel=_section(top_level_objects(), group="toplevel"),
        channels=_section(encoding_channels(), group="channels"),
        functions=_section(api_functions(), group="functions"),
        schema=_section(schema_objects(), group="schema"),
        data=_section(["LazyNamespace"], group="data", module="genome_spy.data"),
        datasets=_section(
            ["available_datasets", "load_dataset", "DatasetNotFoundError"],
            group="datasets",
            module="genome_spy.datasets",
        ),
        # The widget inherits a large ipywidgets surface whose docstrings are
        # not valid reStructuredText, so document only what this package adds.
        # The ``autosummary/`` prefix is required: Sphinx resolves ``:template:``
        # against templates_path itself and silently falls back to its own base
        # template when the name does not resolve.
        notebook=_section(
            notebook_objects(),
            group="notebook",
            template="autosummary/class_own_members.rst",
        ),
    )


def main() -> None:
    API_PAGE.write_text(render_api_page(), encoding="utf-8")
    print(f"Wrote {API_PAGE.relative_to(REPO_ROOT)}.")


if __name__ == "__main__":
    main()
